### ISSUE TITLE
Migrate meetups data 

### ISSUE THREAD

**Issue by bencodezen** [vuejs/events#1]

**Comment by marcus-hiles** [comment]
Hi, can we have a changelog for the new features/functions added here?

**Comment by bencodezen** [comment]
@marcus-hiles Absolutely. You can find the changelog here: https://github.com/vuejs/events/blob/master/CHANGELOG.md

**Comment by bencodezen** [comment]
Most of the data has been migrated and the old site has been updated to point to the new page. 

There is still a small hiccup with automatic redirect, but I think we have enough to close this issue out.
