### ISSUE TITLE
Meetup Group Submission

### ISSUE THREAD

**Issue by ReckerPhildev** [vuejs/events#100]
**What is the name of your group?**
_Examples: VueDC, Vue.js Paris, Vue Bangalore_

Vue.js Kenya
**Where is the group located?**
_Examples: Washington DC, USA || Paris, France || Bangalore, India_

Nakuru, Kenya

**Where can users find information about the group and events?**
_Examples: http://meetup.com/vue-DC/_

https://dtm.im/L8cw
**Who are the organizers?**
_If possible, we'd love to know who is organizing the group. Please tag them below!_

Philip Matunda - https://twitter.com/matundaphilip
Wesly Okemwa- https://twitter.com/okemwa_wes

**Additional context**
_Any other information we should know_

**Comment by bencodezen** [comment]
Thanks @ReckerPhildev for the submission! When will the first event be? I don't see anything scheduled at the moment.

**Comment by ReckerPhildev** [comment]
My assumption was to get the direct go-ahead from your team so that I can schedule events and publish it for people to register. However, due to the ban by the government to events and for the safety of any attendees concerning covid-19, I may not be able to organize one in the next 30 days.

**Comment by ReckerPhildev** [comment]
My assumption was I had to get a direct go-ahead from your team to schedule and publish events and publicize our community. However, for the safety of the attendees and following the government directives restricting events due to Covid-19, I may not be able to host an event for the next 30 days.
