### ISSUE TITLE
[Presentation] Find a better way for describe the presentation format.

### ISSUE THREAD

**Issue by AMontagu** [vuejs/events#116]
The PR templating in github in the template repository need a branch in order to work.

Keep the branch up to date may be difficult. 

Implementing an other solutions has plain text text in issue template and a sub PR templating in the presentation repo may be a good choice.

Feel free to present any idea.

**Comment by kissu** [comment]
Thanks on your contribution on that one, I can see that this template now exist: https://github.com/vuejs/events/blob/main/.github/PULL_REQUEST_TEMPLATE/pull-request-presentation.md

I'm hence closing this one. Ping me if something's wrong with it.
