### ISSUE TITLE
Vue.js  Kenya Group

### ISSUE THREAD

**Issue by Mwangii** [vuejs/events#119]
Group Name:
Vue.js Nairobi
Location:
Nairobi, Kenya
find information 
https://www.facebook.com/groups/273869510674650/
Organizer
developermwangii2010@gmail.com

**Comment by bencodezen** [comment]
Thanks @Mwangii for the PR! Do you know when you plan on hosting events?

**Comment by Mwangii** [comment]
Dear Ben,
Currently, the government has restricted meetings,  I shall notify you when
we are in a position to host a meeting or we can plan for an online meetup.
Regards.

**Comment by bencodezen** [comment]
@Mwangii No worries! Yes I didn't mean in person. I'm thinking it would be good to maybe host a remote event? What do you think?

**Comment by Mwangii** [comment]
Yes a remote event will be the best option, due to the current situations.

**Comment by kissu** [comment]
Glad to see that you're now able to [host meetups](https://www.meetup.com/fr-FR/vue-js-kenya/)! 🎊 💪🏻
