### ISSUE TITLE
New St George, UT, USA Group

### ISSUE THREAD

**Issue by harwoodspike** [vuejs/events#124]
**What is the name of your group?:**
Southern Utah Vue.js Meetup

**Where is the group located:**
Saint George, UT, USA

**Where can users find information about the group and events?:**
https://www.meetup.com/Southern-Utah-Vuejs-Meetup/

**Who are the organizers?:**
Joshua Harwood (me)

**Comment by bencodezen** [comment]
That's so great @harwoodspike! Any idea when you all will be hosting your first event?

**Comment by harwoodspike** [comment]
I am in the middle of setup and planning, but I hope to have it scheduled before the end of next week.

I am think of having a remote workshop type event where the participants can bring there project and get help or just show them off.

**Comment by bencodezen** [comment]
@harwoodspike Awesome. Let me know once you have the details ironed out and I'll be glad to help promote it!
