### ISSUE TITLE
Vue Js Nigeria

### ISSUE THREAD

**Issue by promzybankz** [vuejs/events#128]
**What is the name of your group?**
Vue Nigeria

**Where is the group located?**
Nigeria 

**Where can users find information about the group and events?**
None yet.. Meetup.com charges are too expensive for me. I'm still a student in love with Vue

**Who are the organizers?**
https://github.com/promzybankz

Twitter : https://twitter.com/promzybankz

**Additional context**
I Loved Vue from the Moment I got to know about it. I want to spread this love in my Country. Give me a chance

**Comment by bencodezen** [comment]
Hi @promzybankz! Thanks for reaching out. Would love to certainly see more activity as far as hosting a group in Nigeria. What we need as far as next steps is for you to begin hosting events for people to get together. So even though meetup.com isn't a good option, you are certainly welcome to use anything that would be best for you.

If you have any questions, please let me know!

**Comment by promzybankz** [comment]
Sure. We do want to begin hosting events in Nigeria but funds for such meet
ups are high. Do we get any sponsorships from the international body? Can
we get swags and gift items like Vue T shirts, stickers and other items?
These and others re some of the questions I'll like to be cleared on.
Thanks.

**Comment by bencodezen** [comment]
Great questions. In terms of funding, there currently is no official budget for providing financial support for groups around the world. We are working to figure out ways to support meetup organizers with swag and such, but this is still a work in progress.

In the meantime, in terms of setting up events in Nigeria, what are some of the costs that you are encountering for hosting meetups? And how do these costs change if we could provide support via a Zoom webinar that we can reserve for you?

**Comment by promzybankz** [comment]
The major costs involved is the cost of getting a venue, the cost for
providing power (electricity), cost for creating awareness and also for
mobility. Though a Zoom webinar would be very helpful, it can't efficiently
replace a physical meetup as most persons would very love to have a live
hands on training. And of course you know, what's a meetup without swags
and gift items. So these are the costs we are going to encounter as we plan
a meetup here in Nigeria.

**Comment by bencodezen** [comment]
At this time, the Vue.js Events team primarily provides support to groups through awareness as well as remote support. Unfortunately we do not have a budget to support meetups financially at this time.

While I know physical meetups are preferred, given the current pandemic situation, I would encourage trying to grow a community via forum or through the official VueLand Discord at this time. 

If you have any other questions, please let me know!

**Comment by kissu** [comment]
Closing since VueJS Nigeria's [meetup.com page](https://www.meetup.com/fr-FR/vuejs-nigeria/) is now a thing.
Also available in the list of meetups. 😉
