### ISSUE TITLE
Vue.Js Kampala

### ISSUE THREAD

**Issue by fatukunda** [vuejs/events#129]
## Event

**What is your event called?**

Vue Kampala 

**Where is your event located?**

Kampala, Uganda 

## Host Info

**Who are the organizers**

 Frank Atukunda - https://twitter.com/fatukunda 
 Armstrong Muhwezi - https://twitter.com/armstrongsenior
James Mudidi - https://twitter.com/JamesMudidi  

**Where can people learn more about the group (e.g., Meetup.com page, personal site, etc.)?**

To be set up soon

**Comment by bencodezen** [comment]
Thanks for filing the issue @fatukunda! Let me know when you all setup a page for people to learn more about the group as well as upcoming events.

**Comment by kissu** [comment]
Closing in favor of this issue: #176
