### ISSUE TITLE
VueJs Chicago Meetup - Back To School online meetup

### ISSUE THREAD

**Issue by elevatebart** [vuejs/events#132]
## Event

**What is your event called?**

VueJs Chicago Meetup - Back To School online meetup

**Where is your event located?**

Online (Zoom, Youtube, link posted on twitter)

**When is your event happening?**

Sept. 15th 5:30 PM CST

**What is your event about?**

- A GridSome beginners interview overview
- An introduction to vue-formulate

**Where can people learn more about your event / reserve their spot?**

https://www.meetup.com/Chicago-Vue-js/events/272152197/

## Host Info

**Who is hosting this event?**

Bart Ledoux and Daniel Richmond

**Where can people learn more about the group (e.g., Meetup.com page, personal site, etc.)?**

https://www.meetup.com/Chicago-Vue-js/

**Comment by kissu** [comment]
This meetup is done (2020), sorry for the delay. 🙏🏻 
Feel free to post another one, I'll merge it!

PS: the meetup link is already available in the project. 👌🏻
