### ISSUE TITLE
Vuejs Nigeria

### ISSUE THREAD

**Issue by amycruz97** [vuejs/events#136]
**What is the name of your group?**
_Examples:Vuejs Nigeria

**Where is the group located?**
_Examples: Lagos, Nigeria

**Where can users find information about the group and events?**
_Examples: https://www.meetup.com/vuejs-nigeria/_,  https://twitter.com/VuejsNg

**Who are the organizers?**
_If possible, we'd love to know who is organizing the group. Please tag them below!_
@amycruz97, @LindaOjo, @bahdcoder

**Additional context**
_Any other information we should know_

**Comment by kissu** [comment]
Sorry for the delay, I've added it now. 👍🏻
