### ISSUE TITLE
Vuejs Kenya Community

### ISSUE THREAD

**Issue by Phil-Reck** [vuejs/events#137]
**What is the name of your group?**
VueJS Kenya

**Where is the group located?**
Kenya

**Where can users find information about the group and events?**
https://www.meetup.com/vue-js-kenya/
https://twitter.com/KenyaVue

**Who are the organizers?**
Philip Matunda - philipmatunda@gmail.com
Joshua Murigi - joshryggs@gmail.com
Brian Wachira - brianwachira@gmail.com

**Additional context**
The goal is to provide monthly meetups where people give talks on Vue and related topics, do a hands-on activity and people can get together with other developers in the community.

**Comment by kissu** [comment]
Sorry for the delay, I've added it now. 👍🏻

**Comment by Phil-Reck** [comment]
Thank you!
