### ISSUE TITLE
[CFP]

### ISSUE THREAD

**Issue by faraazmalak** [vuejs/events#145]
## Conference 
Vue.js summit, filled up by Faraaz for testing

## Speaker Amenities

- [ ] Flight expenses covered (up to ...)
- [ ] Hotel expenses covered (up to ...)
- [ ] Speaker dinner
- [ ] {{ insertMoreHere }}

**Comment by kissu** [comment]
Hi! 👋🏻 
Sorry for the latest feedback. I think it's not useful to merge that one now.
Feel free to post a new one tho! 🙏🏻
