### ISSUE TITLE
Meetup Group Submission

### ISSUE THREAD

**Issue by saad96-disign** [vuejs/events#147]
**What is the name of your group?**
vuejsOuagadougou

**Where is the group located?**
Burkina Faso, Ouagadougou

**Where can users find information about the group and events?**
Currently we use Facebook :https://www.facebook.com/vuejsOuagadougou, but we plan to use Instagram, Zoom and WhatsApp Channel because these are the most used in our country

**Who are the organizers?**
https://www.github.com/saad96-disign
https://www.github.com/xsmael

**Additional context**
Lovers of front end development and considering the ease of learning #vuejs, we decided to create this community which will allow all enthusiasts in my country and elsewhere to transmit and receive knowledge through different activities.

**Comment by kissu** [comment]
This one was merged in #175. 🎊
