### ISSUE TITLE
[CFP] VueJS London

### ISSUE THREAD

**Issue by PixelsCommander** [vuejs/events#160]
## Conference 
VueJS London

## CFP Link
https://forms.gle/MyHUPCyiiNUj9Aht8

## Speaker Amenities
- [x] Flight expenses covered (up to 500GBP)
- [x] Hotel expenses covered (up to 500GBP)
- [x] Speaker dinner

**Comment by kissu** [comment]
Sorry that this wasn't merged. I guess it's useless to add it now.
I'll probably add the 2022's one myself! 👍🏻
