### ISSUE TITLE
[Event] VueJS London

### ISSUE THREAD

**Issue by PixelsCommander** [vuejs/events#161]
## Event
VueJS London

**Where is your event located?**
UK, London + Online

**When is your event happening?**
20-21 October 2021

**What is your event about?**

VueJS community gathering in London

**Where can people learn more about your event / reserve their spot?**
https://vuejs.london/

## Host Info

**Who is hosting this event?**

GitNation Foundation

**Where can people learn more about the group (e.g., Meetup.com page, personal site, etc.)?**

https://www.meetup.com/vuejs-london/

**Comment by kissu** [comment]
Looking at [Meetup's page](https://www.meetup.com/fr-FR/vuejs-london/), there is nothing new planned for the moment.
Feel free to submit when something new is planned!
Thanks. 🙏🏻
