### ISSUE TITLE
[CFP] Vuejs Global 2021

### ISSUE THREAD

**Issue by lauragift21** [vuejs/events#164]
## Conference 

Vuejs Global 2021

## CFP Link

https://docs.google.com/forms/d/e/1FAIpQLSeqycTjNxCMdk9c5vIMB7IxM3odz8fXldmBwsV07l0Ojr1cZw/viewform

CFP Closes on September 1st, 2021

-  [x] Flight expenses covered
 - [X] Hotel expenses covered
 - [X] Speaker dinner

**Comment by kissu** [comment]
Closing because it's already done. 👍🏻
