### ISSUE TITLE
[Event] Vuejs Global

### ISSUE THREAD

**Issue by lauragift21** [vuejs/events#165]
## Event

**What is your event called?**

{{ Vuejs Global }}

**Where is your event located?**

{{ Amsterdam, Netherlands }}

**When is your event happening?**

{{ 1st & 4th October 2021 }}

**What is your event about?**

{{ VUEJS GLOBAL is live and in-person at Theater Amsterdam on the 1st & 4th October 2021 }}

**Where can people learn more about your event/reserve their spot?**

{{ https://www.vuejs.amsterdam/ }}

## Host Info

**Who is hosting this event?**

{{ Passionate People }}

**Where can people learn more about the group (e.g., Meetup.com page, personal site, etc.)?**

{{ https://passionatepeople.io/conferences  }}

**Comment by kissu** [comment]
Hehe, sorry for that one Gift.
I've added the session for 2023 tho (will push it shortly). 👍🏻
