### ISSUE TITLE
New meetup group request: VueJS Ouagadougou

### ISSUE THREAD

**Issue by Xsmael** [vuejs/events#174]
**What is the name of your group?**
VueJS Ouagadougou

**Where is the group located?**
Ouagadougou, Burkina Faso

**Where can users find information about the group and events?**
https://www.facebook.com/vuejsOuagadougou

**Who are the organizers?**
@xsmael @saad96-disign 

**Additional context**
We love VueJS

**Comment by bencodezen** [comment]
PR has been merged! So happy to see a community growing in Ouagadougou. 💚
