### ISSUE TITLE
VueVasity

### ISSUE THREAD

**Issue by katoj65** [vuejs/events#176]
**What is the name of your group?**
_Examples: VueDC, Vue.js Paris, Vue Bangalore_

**Where is the group located?**
_Examples: Washington DC, USA || Paris, France || Bangalore, India_

**Where can users find information about the group and events?**
_Examples: http://meetup.com/vue-DC/_

**Who are the organizers?**
_If possible, we'd love to know who is organizing the group. Please tag them below!_

**Additional context**
_Any other information we should know_

**Comment by kissu** [comment]
Hi! 👋🏻 
From what I can see, this your twitter page: https://twitter.com/VueVasity

Do you have any kind of website, meetup.com page or dates? 🙂
