### ISSUE TITLE
[CFP]

### ISSUE THREAD

**Issue by pantarei-mb** [vuejs/events#189]
## Speakers Pack

- [x] conference ticket, coffee breaks and lunch on the event's day
- [x] a single room for 1 night (2 nights for people coming from outside the European continent)
- [x] Speaker dinner
- [x] a refund of up to €250 for travel costs within Europe (up to €500 outside the European continent)

**Comment by kissu** [comment]
I was actually thinking about putting that one yesterday! 👍🏻

**Comment by kissu** [comment]
Conference + CFP were added in this commit: https://github.com/vuejs/events/commit/c13ccbcb1aeb587d74d48d1ef23acfc71a7c4283#

Thanks! 🙏🏻
