### ISSUE TITLE
[CFP]

### ISSUE THREAD

**Issue by cirpo** [vuejs/events#192]
## Conference 

https://2022.vueday.it/

## CFP Link

https://2022.vueday.it/welcome/cfp.html

## Speaker Amenities

- [x] Flight expenses covered (€250 for travel costs within Europe (up to €500 outside the European continent)
- [x] Hotel expenses covered (a single room for 1 night (2 nights for people coming from outside the European continent))
- [x] Speaker dinner

**Comment by cirpo** [comment]
closing as addressed here
https://github.com/vuejs/events/commit/c13ccbcb1aeb587d74d48d1ef23acfc71a7c4283

**Comment by kissu** [comment]
Sorry, forgot to mention it here! 👍🏻
