### ISSUE TITLE
Southampton - England - Meetup Group

### ISSUE THREAD

**Issue by zamwans** [vuejs/events#200]
**What is the name of your group?**
Vue.js Southampton

**Where is the group located?**
Southampton, Hampshire, England

**Where can users find information about the group and events?**
https://www.meetup.com/vuejs-southampton/

**Who are the organizers?**
Derek Mwanza
https://www.dcmsoftwaredevelopment.co.uk/

**Comment by kissu** [comment]
Sorry for the delay 😅, done [here](https://github.com/vuejs/events/commit/330db9f87d1553c3bd21f4809dc1e47c2b4ff292). ✅
