### ISSUE TITLE
Vuejs Lubumbashi community meetup

### ISSUE THREAD

**Issue by CHRINOVIC-MM** [vuejs/events#202]
**What is the name of your group?**
VueJs Lubumbashi

**Where is the group located?**
Lubumbashi, DRC

**Where can users find information about the group and events?**
https://web.facebook.com/profile.php?id=100091689452990

**Who are the organizers?**
@CHRINOVIC-MM
@ElvinKyungu

We are passionate about web development and using the Vuejs framework, we want to create a Vuejs community for our city to help each other in learning this progressive framework

**Comment by kissu** [comment]
Sorry for the delay 😅, done [here](https://github.com/vuejs/events/commit/330db9f87d1553c3bd21f4809dc1e47c2b4ff292) and live. ✅
