### ISSUE TITLE
Request to open the Vue.js Sri Lanka community

### ISSUE THREAD

**Issue by MadhushaPrasad** [vuejs/events#203]
**What is the name of your group?**
 ***Vue.js Sri Lanka***

**Where is the group located?**
 ***Colombo,Sri Lanka***

**Where can users find information about the group and events?**
**https://www.facebook.com/groups/956997605457925/**
https://github.com/vuejssrilanka

**Who are the organizers?**
@MadhushaPrasad - Community Lead
@Charith47
@yasithWimukthi
@IndudiniThennakoon
@yasirupanduka99

**Additional context**
Our mission is to create a welcoming and inclusive environment for developers of all skill levels to come together and collaborate on building web applications using the Vue.js framework.
Our vision is to create a thriving community of Vue.js developers in Sri Lanka, where members can learn, share their knowledge and experiences, collaborate on projects, and inspire each other to achieve excellence in building web applications using Vue.js. Through regular meetups, workshops, and other events, we aim to foster a culture of continuous learning and innovation, while also promoting the value and potential of Vue.js as a modern and powerful front-end framework. Our goal is to support the growth and development of the local tech ecosystem and contribute to the global Vue.js community.

**Comment by kissu** [comment]
Sorry for being late on that one! 🙏🏻 
Done here: https://github.com/vuejs/events/commit/80c2bbc2fa0aae4854cf2ebf8e1eaaad52c66bdb

**Comment by MadhushaPrasad** [comment]
@kissu thank you for accepting our request

**Comment by IndudiniThennakoon** [comment]
@kissu thank you for accepting our request

**Comment by yasithWimukthi** [comment]
@kissu Thank you for accepting our request

**Comment by yasirupanduka99** [comment]
@kissu Thank you for accepting our request!
