### ISSUE TITLE
Vue Girona Meet up

### ISSUE THREAD

**Issue by jordigasau** [vuejs/events#205]
**What is the name of your group?**
Vue Girona

**Where is the group located?**
Girona, Catalonia, Spain

**Where can users find information about the group and events?**
https://www.meetup.com/vue-js-girona/

**Who are the organizers?**
Jordi Gasau 
https://www.linkedin.com/in/jordigasau/

**Comment by kissu** [comment]
Sorry for the delay 😅, done [here](https://github.com/vuejs/events/commit/330db9f87d1553c3bd21f4809dc1e47c2b4ff292) and live. ✅
