### ISSUE TITLE
[Event]

### ISSUE THREAD

**Issue by cirpo** [vuejs/events#207]
## Event

**What is your event called?**

{{ Vueday }}

**Where is your event located?**

{{ Verona, Italy }}

**When is your event happening?**

{{ 20/11/2023 9 am }}

**What is your event about?**

{{ vueday 2023 is the 5th edition of the Italian Vue conference, from the GrUSP Team - organizer of events like [jsday](https://www.jsday.it/). }}

**Where can people learn more about your event / reserve their spot?**

{{ [url](https://2023.vueday.it/) }}

## Host Info

**Who is hosting this event?**

{{ GrUSP }}

**Where can people learn more about the group (e.g., Meetup.com page, personal site, etc.)?**

{{ [groupWebsite](https://www.grusp.org/en/) }}

**Comment by cirpo** [comment]
@bencodezen  🙏

**Comment by kissu** [comment]
Taking care of this PR this morning! 😸

**Comment by kissu** [comment]
Btw, it's the 10th of November 2023 and not the 20th as you wrote above or did I miss something. 😅 
![image](https://github.com/vuejs/events/assets/5133074/b13fa724-b896-41d1-a8fe-d7bf40e9f1ef)

I'll also added the CFP info. ✅ 

Done [here](https://github.com/vuejs/events/commit/531798be61279af78d13a7b3278bc2cdc4e0dce2) ✅, give it a few moments to fully deploy. 👍🏻

**Comment by cirpo** [comment]
oops, thanks @kissu !
