### ISSUE TITLE
[Event]VueConf CN 2024

### ISSUE THREAD

**Issue by fequancom** [vuejs/events#220]
## Event

**What is your event called?**

{{ VueConf CN 2024 }}

**Where is your event located?**

{{ 中国·深圳 }}

**When is your event happening?**

{{ 2024.07.06 09:00 }}

**What is your event about?**

{{ On July 6, 2024, hosted by the official in Shenzhen, a technology feast will be held for global Vue.js developers. }}

**Where can people learn more about your event / reserve their spot?**

{{ [https://vueconf.cn](https://vueconf.cn) }}

## Host Info

**Who is hosting this event?**

{{ W3CTech & fequan }}

**Comment by kissu** [comment]
Done. 💚

**Comment by fequancom** [comment]
> Done. 💚

Thank you very much!
