### ISSUE TITLE
Add Event Graphics resource

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/events#27]
I'm placing graphics and their source files in google drive (typically too large for GitHub).

* https://drive.google.com/drive/folders/0B1ovWdH4ntFvUXNTRVB2MG1odWc?usp=sharing

These are fairly generic events that can be used on Meetup.com.

The source files have everything on layers and text can be changed to say whatever you want for your event.

They're all made in [Photopea](https://photopea.com) (free, browser-based alternative to Photoshop), so you do not need Photoshop to edit them.

**Comment by TheJaredWilcurt** [comment]
Example graphic in use:

* https://www.meetup.com/vuejsindy/events/261422246/

**Comment by bencodezen** [comment]
These are great! Do you want to issue a PR to add it to the Resources guide of the site?

If you don't have the time, I'm happy to help out!

**Comment by TheJaredWilcurt** [comment]
I figured it would go under the Resources menu:

![resources menu](https://user-images.githubusercontent.com/4629794/58833645-7b2a7900-861f-11e9-8564-42058ba4990c.png)

Don't know where that is in the code. You can do it.

**Comment by bencodezen** [comment]
You got it. Thanks for submitting this @TheJaredWilcurt!
