### ISSUE TITLE
The meetup list made a serious political mistake

### ISSUE THREAD

**Issue by mqhe2007** [vuejs/events#29]
### The meetup list made a serious political mistake,Hong Kong and Taiwan are an inseparable part of China🇨🇳!

**Comment by bencodezen** [comment]
Hello! Thank you for raising this issue. I've gone ahead and updated the content to ensure that the location mapping is correct. Appreciate it!

**Comment by suensummit** [comment]
> ## 聚会列表犯了一个严重的政治错误，香港和台湾是中国🇨🇳不可分割的一部分！
> ### The meetup list made a serious political mistake,Hong Kong and Taiwan are an inseparable part of China🇨🇳!

You should not allow to visit Github by law.

**Comment by Nelson119** [comment]
台灣、中國，一邊一國。

**Comment by advancedor96** [comment]
![image](https://user-images.githubusercontent.com/1284933/58535538-daa01780-8220-11e9-8e92-75d6fdf22c7d.png)

**Comment by HuarenYu** [comment]
@Nelson119 Taiwan is not a legal country in United Nations

**Comment by mqhe2007** [comment]
> > ## 聚会列表犯了一个严重的政治错误，香港和台湾是中国🇨🇳不可分割的一部分！
> > ### The meetup list made a serious political mistake,Hong Kong and Taiwan are an inseparable part of China🇨🇳!
> 
> You should not allow to visit Github by law.

中国大陆哪条法律禁止我访问github了？请指出来。

**Comment by Nelson119** [comment]
> @Nelson119 Taiwan is not a legal country in United Nations

THAT'S WHY UN WOULDN'T AND CAN'T SPEAK FOR TAIWAN.

**Comment by Nelson119** [comment]
建立獨立國家是國際人權公約裡規範的國際人權

**Comment by HuarenYu** [comment]
@Nelson119 你可以建国，但请不要在台湾岛建，因为那是中国的领土，现在台湾的合法政府是中华民国政府。

**Comment by SummerFans** [comment]
republic of China not republic of taiwan

**Comment by yuu2lee4** [comment]
台湾目前不是中华民国代管么，民国宪法里台湾只是整个领土的一部分吧，中华台北这样的说法还比较能接受哦

**Comment by Nelson119** [comment]
民國憲法領土沒有包含台灣，只是代管而已

**Comment by Nelson119** [comment]
乾脆說中南半島跟朝鮮半島都中國領土好了

**Comment by Tassis** [comment]
這裡是屬於開源的地方別把你們醜陋的意識形態帶出來行嘛？

**Comment by Nelson119** [comment]
一心想併吞別人能不醜陋嗎

**Comment by yuu2lee4** [comment]
总之分裂是不可能分裂的。。。不想做中华儿女的不肖子孙以后就移民吧

**Comment by zhangkai-2015** [comment]
狗杂种！写着汉语，说着汉语，还搞台独，搞分裂，当我入台湾省的时候我不会放过你。

**Comment by HuarenYu** [comment]
@Nelson119 我们并没有要吞并谁，现状就是中华民国政府是台湾的合法政府，你的护照上都是中华民国。
请不要用你丑陋的思想胡乱推测我们要吞并谁

**Comment by HuarenYu** [comment]
@zhangkai-2015 好好辩论，别骂人

**Comment by SummerFans** [comment]
/China/ig.test('Republic of China') => true

**Comment by Tassis** [comment]
你們是 P.R.C 來著...?

**Comment by zhangkai-2015** [comment]
无须辩论，不可否认的事实，台湾省，必须变红。

**Comment by ziyofun** [comment]
@bencodezen Can you only put continents and cities in the list, technology to technology, politics to politics.

**Comment by kevin940726** [comment]
@bencodezen Please lock this conversation as it's not getting anywhere related to the repo.

**Comment by Tassis** [comment]
@kevin940726  agree

**Comment by zhangkai-2015** [comment]
有没有想过如果统一了，你们这帮人准备怎么安放自己。

**Comment by ronail** [comment]
@mqhe2007 @HuarenYu just fork the repo and put whatever county you want under China to please yourselves.
Spreading misleading information over the internet does not make you stronger. It just puts your country to shame

**Comment by ilake** [comment]
https://www.reddit.com/r/Jokes/comments/bthmbs/hey_i_heard_china_just_legalized_samesex_marriage/

**Comment by bencodezen** [comment]
@ziyofun Thanks for the suggestion. I am definitely going to restructure the page accordingly moving forward to keep the politics out of it.

@kevin940726 Done
