### ISSUE TITLE
尤雨溪团队把台湾和香港与中国同列,难道不出来解释一下?

### ISSUE THREAD

**Issue by maiglail** [vuejs/events#33]
任何一个中国人都能分得清的问题,你们竟然如此做,很难让人想到是粗心大意,,,,,一切小伎俩都是枉然!!!!

**Comment by zgayjjf** [comment]
Please lock this conversation.

**Comment by unixzii** [comment]
Don't take politics into the community, if you don't want to use Vue.js, just go and choose others.

**Comment by bencodezen** [comment]
Please note that the meetup list prioritizes users' ability to quickly locate the regions they identify with - the structure does not imply any specific political views.

This disclaimer has now been added with https://github.com/vuejs/events/commit/03b07ec65255caa109fd86dce2f62e391c19e415
