### ISSUE TITLE
举报地址

### ISSUE THREAD

**Issue by yutao331763646** [vuejs/events#34]
![举报途径.png](https://upload-images.jianshu.io/upload_images/11430115-c293f8ba0930ccc2.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by bencodezen** [comment]
Please note that the meetup list prioritizes users' ability to quickly locate the regions they identify with - the structure does not imply any specific political views.

This disclaimer has now been added with https://github.com/vuejs/events/commit/03b07ec65255caa109fd86dce2f62e391c19e415
