### ISSUE TITLE
Add MSK VUE.JS

### ISSUE THREAD

**Issue by irbisadm** [vuejs/events#35]
**What is the name of your group?**
MSK VUE.JS

**Where is the group located?**
Moscow, Russia

**Where can users find information about the group and events?**
https://voximplant.timepad.ru/event/986750/ (russian version of meetups.org also we are plannig to cheate public chat atlocal messenger)
https://www.meetup.com/MSK-VUE-JS/

**Who are the organizers?**
@voximplant @irbisadm @AlcaZeltser

**Additional context**
We are planning our event according your guide. Already we've got speakers for the few event. Voximplant hosts us and provide the food and live stream, so we can share the videos with the community and will be really glad if you can help us with some info partnership

**Comment by bencodezen** [comment]
Welcome to the community! Excited to have you all on board and definitely keep us posted as far as events so we can help share on Twitter and the site. I should have this updated in the site by the end of the week. Let me know if you have any questions or need anything else in the meantime!
