### ISSUE TITLE
why meetup locations grouped for Japan, India, but not for China?

### ISSUE THREAD

**Issue by lab4quant** [vuejs/events#36]
why meetup locations grouped for Japan, India, but not for China?

I saw similar tickets closed and locked, with comments like to help user to locate meeting quickly and not to project any political view.

if that's the case, it should be the same for other countries like Japan and India

care to explain why different rule for China?

![image](https://user-images.githubusercontent.com/29996911/58605087-450c9280-82c9-11e9-8771-906219df89a5.png)

**Comment by sky20054122** [comment]
美国的小动作真多啊！  怎么不把美国分成几个来展示？

**Comment by beetaa** [comment]
@bencodezen I know the pionts that the list is non-political relates, but please take the constant rule to sort the list, as NON-POLITICAL you mean! what's the rules or standards you're using? by continent? by country? or by what? if you cannot give the rules, there's no way to get people you done right!

**Comment by w1ndy** [comment]
How about using a list of cities sorted alphabetically instead? Just to avoid further political arguments.

**Comment by kurotanshi** [comment]
Maybe we can use map to present locations of meetup, just like VuePeople.org ?

**Comment by unixzii** [comment]
Take a look at how Apple is doing, is there anything wrong? Let me tell you, the locations are grouped by country or region.

<img width="1039" alt="屏幕快照 2019-05-30 14 38 39" src="https://user-images.githubusercontent.com/3109144/58613552-a55efc80-82e8-11e9-8f8b-0722b721664f.png">

**Comment by moss1991** [comment]
@beetaa  claimming NON-POLITICAL in document BUT list Mainland Hongkong and Taiwan as coutries, your behavior is **SUCK**

**THERE IS ONLY ONE CHINA IN UNITED NATIONS**

If you really want NON-POLITICAL , change document like this

* china
 * * Bejing
 * * HongKong
 * * Taiwan
* India
* * ...

or

* city
* * Bejing
* * HongKong
* * Taiwan
* * ...

and map is a good idea.

@beetaa There is so many ways to make document look more comfortable, but what you have done make everyone disappointed

**Comment by gwenchou** [comment]
@moss1991 Yes, absolutely, there's only one China in UN, but Taiwan is not a part of China (So Taiwan is not in UN) and Taiwan's government is not ruled by China either.

So for NON-POLITICAL and according to reality, change the list like this:

* ~~Mainland~~ China
  * Bejing
  * Hong Kong
* Taiwan
  * Taipei
* India
....

**Comment by lab4quant** [comment]
@gwenchou, it's not `one China in UN`, it's `one China everywhere`
you're right Taiwan is not in UN, because it's not a country, it never was and it never will be.

**Comment by yyx990803** [comment]
1. The list contains both countries AND regions.

2. The list prioritizes how users identifies themselves as "from a certain region". Historically and culturally, people living in Hong Kong and Taiwan first identify themselves as "from Hong Kong" or "from Taiwan". If the listing makes it easier for users to find their respective locations then that's the way it will be listed. This is unrelated to "which region is part of which". As far as we know, countries like Japan or India do not have this unique situation.

3. Politics is complicated. You can claim that Taiwan is part of China, when in fact it is not actually ruled by the PRC government and its citizens travel with a different passport that is recognized by most of the world, and YOU as a citizen of China needs a visa to go to Taiwan. You may think Taiwan should be listed under China, when users from Taiwan thinks the other way around. This whole thing is controversial and as a project Vue tries to be as neutral as possible. In trying to do that, we have to look at what international organizations doing. And if you do that yourself you will notice the way we are listing them right now is adopted by almost all international companies like Apple, Google, Facebook, Microsoft etc. If you think that's wrong, you should probably stop using anything they make (mind you, that includes iOS, Android, Windows, macOS, VSCode, oh... and GitHub). [Olympics lists Chinese Taipei separately from China](https://www.olympic.org/national-olympic-committees) as well. I'm pretty sure all these international organizations also want to take a neutral stance on this matter, and this is what they have commonly adopted, and that is what we are adopting as well.

4. Trying to argue against this commonly adopted convention in an open source project is probably the most political thing you can do. If you really believe open source should be non-political, please stop that.
