### ISSUE TITLE
[CFP] INTERCOM VUE.JS

### ISSUE THREAD

**Issue by irbisadm** [vuejs/events#45]
## Conference 
INTERCOM VUE.JS
https://vue.intercomconf.com/#

## CFP Link
https://docs.google.com/forms/d/e/1FAIpQLSesonAa4NJSYjvUhcE3wiPgvTQQK9AF_hV4LX2BuOKNWJNC2A/viewform

## Speaker Amenities

- [+] Flight expenses covered (up to $1000)
- [+] Hotel expenses covered (up to $300)
- [+] Speaker dinner
- [+] Visa support
- [+] Tour over the city (optional)

**Comment by tessamero** [comment]
Added the CFP here: https://github.com/vuejs/events/tree/master/src/call-for-proposals

I looked all over the social media, CFP link, and the main conference homepage, and I am unable to find the information about when the CFP closes. Maybe the translation from Russian to English didn't go well for me. May I get that information so I can update the page?

**Comment by irbisadm** [comment]
Thank you! CFP closes at September 1st.

Can you please, change the CFP link to this https://docs.google.com/forms/d/e/1FAIpQLSemqJRsnBp4MzC-25qkNs1_-KBri7kc2ALTea1KPB3gBn2XvA/viewform ?

**Comment by tessamero** [comment]
Done:)
