### ISSUE TITLE
[Event] MSK VUE.JS MEETUP #1

### ISSUE THREAD

**Issue by irbisadm** [vuejs/events#46]
## Event

What is your event called?

MSK VUE.JS MEETUP#1

Where is your event located?

Moscow, Russia

When is your event happening?

July 18th, 2019

What is your event about?

meetup

Where can people learn more about your event / reserve their spot?

https://www.meetup.com/MSK-VUE-JS/events/261865578/

## Host Info

Who is hosting this event?

MSK VUE.JS

Where can people learn more about the group (e.g., Meetup.com page, personal site, etc.)?

https://msk-vuejs.ru/events/ev1.html

**Comment by tessamero** [comment]
Hello! Thanks for submitting. For future reference, you do not need to add individual meetup events. We only add each event if it's a conference. As for meetups, we only add one link per meetup that takes you to the main meetup page of your group.
