### ISSUE TITLE
[Event] MSK VUE.JS MEETUP#2

### ISSUE THREAD

**Issue by irbisadm** [vuejs/events#47]
## Event

What is your event called?

MSK VUE.JS MEETUP#2

Where is your event located?

Moscow, Russia

When is your event happening?

August 15th, 2019

What is your event about?

meetup

Where can people learn more about your event / reserve their spot?

https://www.meetup.com/MSK-VUE-JS/events/261865578/

## Host Info

Who is hosting this event?

MSK VUE.JS

Where can people learn more about the group (e.g., Meetup.com page, personal site, etc.)?

https://msk-vuejs.ru/events/ev2.html

**Comment by tessamero** [comment]
Hello! Thanks for submitting. For future reference, you do not need to add individual meetup events. We only add each event if it's a conference. As for meetups, we only add one link per meetup that takes you to the main meetup page of your group.

**Comment by bencodezen** [comment]
@tessamero At the moment, we're going to keep manually adding events until we have a better automated solution. I'll go ahead and take care of this one in the meantime. Thanks for your attention to this!

**Comment by bencodezen** [comment]
Thanks @irbisadm for submitting this. Your event is now on the site!
