### ISSUE TITLE
[Event] INTERCOM VUE.JS 

### ISSUE THREAD

**Issue by irbisadm** [vuejs/events#49]
## Event

What is your event called?

INTERCOM VUE.JS 

Where is your event located?

Moscow, Russia

When is your event happening?

November 14th, 2019

What is your event about?

conference

Where can people learn more about your event / reserve their spot?

https://vue.intercomconf.com/

## Host Info

Who is hosting this event?

MSK VUE.JS

Where can people learn more about the group (e.g., Meetup.com page, personal site, etc.)?

https://vue.intercomconf.com/

**Comment by tessamero** [comment]
Added!
