### ISSUE TITLE
Vue.js - Columbia

### ISSUE THREAD

**Issue by johnchapmansc** [vuejs/events#50]
**What is the name of your group?**
Columbia Vue.js Meetup Group

**Where is the group located?**
Columbia, South Carolina -  United States

**Where can users find information about the group and events?**
https://www.meetup.com/Columbia-Vue-js-Meetup-Group/

**Who are the organizers?**
John Chapman and Jerry Merchand

**Additional context**
None

**Comment by tessamero** [comment]
Updated the meetup list.
