### ISSUE TITLE
Submit VueJS Athens meetup group

### ISSUE THREAD

**Issue by fakiolinho** [vuejs/events#54]
**What is the name of your group?**

VueJS Athens

**Where is the group located?**

Athens, Greece

**Where can users find information about the group and events?**

https://www.meetup.com/vuejsathens/

**Who are the organizers?**

- @sergiokag
- @emazyka
- @fadamakis
- @dzotos
- @fakiolinho

**Additional context**

We love VueJS!!

**Comment by bencodezen** [comment]
Thank you for filing an issue! Your group has now been added to the site!
