### ISSUE TITLE
Vue San Diego Meetup

### ISSUE THREAD

**Issue by Stegosource** [vuejs/events#57]
**What is the name of your group?**
Vue SD (part of the larger San Diego JavaScript group)

**Where is the group located?**
San Diego, California, USA

**Where can users find information about the group and events?**
https://www.meetup.com/sandiegojs/

**Who are the organizers?**
Austin Gil: @stegosource
Jason Land: @wishinghand

**Additional context**
The current list has an entry for "San Diego VueJS Meetup". This is the same meetup, but it has merged with the larger San Diego JavaScript meetup. We still meet once a month and still run by the same folks.

**Comment by tessamero** [comment]
Is everything good here @Stegosource? let me know and i will close the issue.

**Comment by Stegosource** [comment]
Yep. Sorry, I did not see the commit that fixed it.
