### ISSUE TITLE
Vue.js Aarhus meetup group

### ISSUE THREAD

**Issue by simoneldevig** [vuejs/events#66]
**What is the name of your group?**
Vue.js Aarhus

**Where is the group located?**
Aarhus, Denmark

**Where can users find information about the group and events?**
https://www.meetup.com/vue-js-aarhus/

**Who are the organizers?**
The meetups are organized by myself (@simoneldevig) in collaboration with people from the companies who sponsors and host the different meetups.

**Comment by bencodezen** [comment]
Thank you for submitting an issue @simoneldevig! It should be live on the site soon!
