### ISSUE TITLE
VueJs Rajkot, India

### ISSUE THREAD

**Issue by chintanbanugaria** [vuejs/events#73]
**What is the name of your group?**
_Examples: VueDC, Vue.js Paris, Vue Bangalore_
Vue Rajkot

**Where is the group located?**
_Examples: Washington DC, USA || Paris, France || Bangalore, India_
Rajkot, India

**Where can users find information about the group and events?**
_Examples: http://meetup.com/vue-DC/_
https://rjt.vue.community

**Who are the organizers?**
_If possible, we'd love to know who is organizing the group. Please tag them below!_
Currently myself (@chintanbanugaria) is organizing the meetup. We have two more volunteers whom I shall add them in the website

**Additional context**
_Any other information we should know_

**Comment by bencodezen** [comment]
Thank you for opening an issue and welcome to the community! Feel free to reach out if you have any questions!

**Comment by m4mum** [comment]
@chintanbanugaria  Hey Chintan, Raxit this side, Studied in Rajkot and then moved to Mumbai (Bombay India for 15yrs), now back to Rajkot.  I was planner of Barcamp Mumbai 2,3,4...etc, Early contributor @ headstart (just google my name :-)    Shout out for any help... I am on raxit@m4mum.com (will pass my contact over email...or you can easily get it by google search :-)
