### ISSUE TITLE
Meetup Group Submission

### ISSUE THREAD

**Issue by tolerious** [vuejs/events#74]
**What is the name of your group?**
VueJS Shanghai

**Where is the group located?**
5/F, building E, Hongqiao Green Valley Plaza, No. 669 Shen Gui Road, Minhang,
Shanghai, China

**Where can users find information about the group and events?**
https://groups.google.com/forum/#!forum/vuejs-shanghai/new
Later, we will have a website for our group called [VueJS Shanghai](http://sh.vuejs.city)

**Who are the organizers?**
@tolerious
email:tolerious@qq.com/helong.feng@qorosauto.com
weibo:[坏时少爷](https://weibo.com/51682963)

**Additional context**
There are many people who use Vue.js in Shanghai, so I want to hold a meetup group. Sharing Vue.js skills and working experience.

**Comment by bencodezen** [comment]
@tolerious Thank you for opening up the issue! Could you let me know when the website is live? We can't update the site with the information until we can verify that the site is live so that people don't get confused. 

Looking forward to the seeing the site!

**Comment by tolerious** [comment]
Sure, the domain is registing for ICP backup.  And will be online this weekend on November 10th.

**Comment by tolerious** [comment]
@bencodezen hi, the [Shanghai VueJS Group Website](https://vuejs.walkincity.cn/) is online, anything else should I offer next step?

**Comment by bencodezen** [comment]
@tolerious That's good for now! Thank you for getting this up and wishing you all the best with the meetup. Let us know if you have any questinos!

**Comment by bencodezen** [comment]
Also, I noticed you have a Google Groups link included in the issue, but this is not public to people, so make sure that you keep the public website updated with the meetup information or ways for people to get that information.

**Comment by tolerious** [comment]
@bencodezen Thank you, I will keep the public website updated, and also will hold some meetups in Shanghai later.
