### ISSUE TITLE
Laravel Live Ahmedabad

### ISSUE THREAD

**Issue by dekts** [vuejs/events#98]
**What is the name of your group?**
_Laravel Live Ahmedabad_

**Where is the group located?**
_Ahmedabad, India_

**Where can users find information about the group and events?**
_https://allevents.in/org/laravel-ahmedabad-community/_

**Who are the organizers?**
_The meetup is organized by ViitorCloud (https://viitorcloud.com/)_

**Additional context**
_We (ViitorCloud Technologies PVT. LTD.) would like to welcome you to attend Vue Meetup we will be organizing every month to be a good part of the growing community._

**Comment by bencodezen** [comment]
Hi @dekts! I checked the link you sent and it seems like it is broken. Can you verify this for me and get back to me when you have a live page? Thanks!

**Comment by dekts** [comment]
Hello @bencodezen 

Please verify the below URLs.

https://laravellive.in/
https://laracon.in/

**Comment by kissu** [comment]
Hi @dekts! 👋🏻 
Sorry for the late reply. Do you have a VueJS meetup/conference/event to share still? 🙂
